- name: install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: start and enable the mysql service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Install python mysql dependencies
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3.9  # pip3.11 if python version is 3.11

# check password is already setup
- name: check the connection to db
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{mysql_root_password}}"
    login_host: "{{login_host}}"
    filter: version
  ignore_errors: yes
  register: mysql_connection_output

- name: Setup root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass "{{mysql_root_password}}"
  when: mysql_connection_output.failed is true   # dont use {{}} in when condition
